zefix:
  outputs:
    dev:
      type: snowflake
      # Credentials are managed by Snowflake - no need to specify account, user, password
      role: accountadmin
      database: zefix
      schema: dev
      warehouse: zefix_dbt_wh
      threads: 4
      keepalives_idle: 30
      search_path: 'zefix.dev'
      
    prod:
      type: snowflake
      # Credentials are managed by Snowflake - no need to specify account, user, password
      role: accountadmin
      database: zefix
      schema: prod
      warehouse: zefix_dbt_wh
      threads: 8
      keepalives_idle: 30
      search_path: 'zefix.prod'
      
  target: dev