zefix:
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: zefix
      schema: dev
      warehouse: task_wh
      
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: zefix
      schema: prod
      warehouse: task_wh
      
  target: dev