zefix:
  outputs:
    dev:
      type: snowflake
      # Credentials are managed by Snowflake - no need to specify account, user, password
      role: accountadmin
      database: zefix
      schema: dev
      warehouse: task_wh
      
    prod:
      type: snowflake
      # Credentials are managed by Snowflake - no need to specify account, user, password
      role: accountadmin
      database: zefix
      schema: prod
      warehouse: task_wh
      
  target: dev