name: 'dbt_semantic_view_converter'
version: '1.0.0'
config-version: 2

require-dbt-version: ">=1.0.0"

macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

dispatch:
  - macro_namespace: dbt_semantic_view_converter
    search_order: ['dbt_semantic_view_converter']
  - macro_namespace: dbt_utils
    search_order: ['dbt_semantic_view_converter', 'dbt_utils']