version: 2

models:
  - name: silver_zefix_companies_raw
    description: "Silver layer raw data extraction from ZEFIX JSON variants - first transformation layer using LOADED_AT for incremental processing"
    columns:
      - name: _loaded_at
        description: "Timestamp when the record was loaded into source system (from LOADED_AT column)"
        tests:
          - not_null
      - name: _content_hash
        description: "MD5 hash of the original JSON content for change detection"
        tests:
          - not_null
      - name: uid
        description: "Unique Company Identification (UID) - Swiss enterprise identifier in format CHE-###.###.###"
        tests:
          - not_null
      - name: uid_formatted
        description: "Formatted UID with dashes for better readability"
      - name: chid
        description: "Company House Identification (CHID) - numeric identifier for companies"
      - name: chid_formatted
        description: "Formatted CHID with dashes for better readability"
      - name: ehraid
        description: "Electronic HR Archive Identification - internal reference number"
      - name: company_name
        description: "Official registered name of the company"
        tests:
          - not_null
      - name: legal_form_id
        description: "Legal form identifier (see documentation for mapping)"
      - name: legal_seat
        description: "Official legal seat/domicile of the company"
      - name: legal_seat_id
        description: "Numeric identifier for the legal seat location"
      - name: register_office_id
        description: "Identifier of the commercial register office"
      - name: company_status
        description: "Current status: EXISTIEREND (Active) or GELOESCHT (Deleted)"
      - name: company_purpose
        description: "Business purpose and activities as stated in commercial register"
      - name: shab_date
        description: "Date of publication in SHAB (Swiss Official Gazette of Commerce)"
      - name: shab_publications_json
        description: "JSON array containing all SHAB publications for this company"
      - name: cantonal_excerpt_web_url
        description: "URL to the cantonal commercial register excerpt"
      - name: delete_date
        description: "Date when the company was deleted/dissolved (if applicable)"
      - name: rab_id
        description: "Register of Auditing Bodies identifier (if applicable)"
      - name: full_content_json
        description: "Complete original JSON content for reference and debugging"

  - name: silver_companies
    description: "Silver layer table with cleaned and structured company data using LOADED_AT for incremental processing"
    columns:
      - name: company_uid
        description: "Primary key - Unique Company Identification from ZEFIX"
        tests:
          - not_null
          - unique
      - name: company_uid_formatted
        description: "User-friendly formatted UID with dashes"
      - name: company_chid
        description: "Company House Identification number"
      - name: company_chid_formatted
        description: "Formatted CHID with dashes"
      - name: company_ehraid
        description: "Electronic HR Archive Identification"
      - name: company_name
        description: "Cleaned official company name (trimmed whitespace)"
        tests:
          - not_null
      - name: legal_form_id
        description: "Legal form identifier (1-8, see legal_forms seed for mapping)"
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8]
      - name: legal_form_name
        description: "German name of legal form (from legal_forms seed)"
      - name: legal_form_name_en
        description: "English name of legal form (from legal_forms seed)"
      - name: abbreviation
        description: "Legal form abbreviation (e.g., AG, GmbH) from legal_forms seed"
      - name: legal_seat
        description: "Cleaned legal seat location"
      - name: legal_seat_id
        description: "Numeric identifier for legal seat"
      - name: register_office_id
        description: "Commercial register office identifier"
      - name: company_status
        description: "Standardized company status (EXISTIEREND or GELOESCHT)"
        tests:
          - accepted_values:
              values: ['EXISTIEREND', 'GELOESCHT']
      - name: company_purpose
        description: "Cleaned business purpose description"
      - name: address_organisation
        description: "Cleaned organization name in address"
      - name: address_care_of
        description: "Cleaned care of information"
      - name: address_street
        description: "Cleaned street name"
      - name: address_house_number
        description: "Cleaned house number"
      - name: address_po_box
        description: "Cleaned PO box information"
      - name: address_zip_code
        description: "Cleaned Swiss postal code"
      - name: address_town
        description: "Cleaned town/city name"
      - name: address_country
        description: "Standardized country code (uppercase)"
      - name: address_addon
        description: "Cleaned additional address information"
      - name: shab_date
        description: "Parsed SHAB publication date"
      - name: delete_date
        description: "Parsed company deletion date"
      - name: cantonal_excerpt_web_url
        description: "URL to cantonal register excerpt"
      - name: rab_id
        description: "Register of Auditing Bodies ID"
      - name: is_active
        description: "Boolean flag indicating if company is currently active"
        tests:
          - not_null
      - name: is_deleted
        description: "Boolean flag indicating if company has been deleted"
        tests:
          - not_null
      - name: _loaded_at
        description: "Timestamp of data loading from source system"
      - name: _content_hash
        description: "Hash of original content for tracking changes"

  - name: silver_shab_publications
    description: "Silver layer table with normalized SHAB (Swiss Official Gazette) publications using LOADED_AT for incremental processing"
    columns:
      - name: company_uid
        description: "Foreign key to silver_companies"
        tests:
          - not_null
          - relationships:
              to: ref('silver_companies')
              field: company_uid
      - name: shab_id
        description: "Unique SHAB publication identifier"
        tests:
          - not_null
      - name: shab_number
        description: "SHAB gazette number"
      - name: shab_date
        description: "Date of SHAB publication"
        tests:
          - not_null
      - name: shab_page
        description: "Page number in SHAB gazette"
      - name: shab_mutation_status
        description: "Status code for the mutation"
      - name: registry_office_id
        description: "ID of the commercial register office"
      - name: registry_office_canton
        description: "Swiss canton abbreviation (e.g., ZH, BE, GE)"
        tests:
          - not_null
      - name: registry_office_journal_date
        description: "Date of commercial register journal entry"
      - name: registry_office_journal_id
        description: "Commercial register journal entry ID"
      - name: publication_message
        description: "Full text of the SHAB publication"
      - name: mutation_types_json
        description: "JSON array of mutation types for downstream processing"
      - name: _loaded_at
        description: "Timestamp of data loading from source system"
      - name: _content_hash
        description: "Hash of original content for tracking changes"

  - name: silver_mutation_types
    description: "Silver layer table with individual mutation types extracted from SHAB publications using LOADED_AT for incremental processing"
    columns:
      - name: company_uid
        description: "Foreign key to silver_companies"
        tests:
          - not_null
          - relationships:
              to: ref('silver_companies')
              field: company_uid
      - name: shab_id
        description: "Foreign key to silver_shab_publications"
        tests:
          - not_null
      - name: mutation_type_id
        description: "Numeric identifier for the mutation type"
        tests:
          - not_null
      - name: mutation_type_key
        description: "Text key describing the type of mutation/change"
        tests:
          - not_null
      - name: shab_date
        description: "Date of SHAB publication (inherited from parent publication)"
      - name: registry_office_canton
        description: "Swiss canton abbreviation (inherited from parent publication)"
      - name: _loaded_at
        description: "Timestamp of data loading from source system"
      - name: _content_hash
        description: "Hash of original content for tracking changes"

seeds:
  - name: legal_forms
    description: "Reference data for Swiss legal forms with German/English names and abbreviations"
    columns:
      - name: legal_form_id
        description: "Numeric identifier for legal form (1-8)"
        tests:
          - not_null
          - unique
      - name: legal_form_name_de
        description: "German name of the legal form"
        tests:
          - not_null
      - name: legal_form_name_en
        description: "English translation of the legal form"
        tests:
          - not_null
      - name: abbreviation
        description: "Common abbreviation (e.g., AG, GmbH) - may be null for forms without standard abbreviations"
      - name: description
        description: "Detailed description of the legal form in English"
        tests:
          - not_null 