version: 2

models:
  - name: bronze_zefix_companies
    description: "Bronze layer table containing raw ZEFIX company data extracted from JSON variants"
    columns:
      - name: _loaded_at
        description: "Timestamp when the record was loaded into the bronze layer"
        tests:
          - not_null
      - name: _content_hash
        description: "MD5 hash of the original JSON content for change detection"
        tests:
          - not_null
          - unique
      - name: uid
        description: "Unique Company Identification (UID) - Swiss enterprise identifier in format CHE-###.###.###"
        tests:
          - not_null
          - unique
      - name: uid_formatted
        description: "Formatted UID with dashes for better readability"
      - name: chid
        description: "Company House Identification (CHID) - numeric identifier for companies"
      - name: chid_formatted
        description: "Formatted CHID with dashes for better readability"
      - name: ehraid
        description: "Electronic HR Archive Identification - internal reference number"
      - name: company_name
        description: "Official registered name of the company"
        tests:
          - not_null
      - name: legal_form_id
        description: |
          Legal form identifier:
          1 = Einzelunternehmen (Sole Proprietorship)
          2 = Kollektivgesellschaft (General Partnership)
          3 = Aktiengesellschaft (Corporation/Stock Company)
          4 = Kommanditgesellschaft (Limited Partnership)
          5 = Gesellschaft mit beschränkter Haftung (Limited Liability Company)
          6 = Genossenschaft (Cooperative)
          7 = Verein (Association)
          8 = Stiftung (Foundation)
      - name: legal_seat
        description: "Official legal seat/domicile of the company"
      - name: legal_seat_id
        description: "Numeric identifier for the legal seat location"
      - name: register_office_id
        description: "Identifier of the commercial register office"
      - name: company_status
        description: |
          Current status of the company:
          EXISTIEREND = Active/Existing
          GELOESCHT = Deleted/Dissolved
      - name: company_purpose
        description: "Business purpose and activities of the company as stated in commercial register"
      - name: address_organisation
        description: "Organization name in the address (if different from company name)"
      - name: address_care_of
        description: "Care of (c/o) information in the address"
      - name: address_street
        description: "Street name of the company address"
      - name: address_house_number
        description: "House number of the company address"
      - name: address_po_box
        description: "Post office box number if applicable"
      - name: address_zip_code
        description: "Swiss postal code"
      - name: address_town
        description: "Town/city name"
      - name: address_country
        description: "Country code (typically CH for Switzerland)"
      - name: address_addon
        description: "Additional address information"
      - name: shab_date
        description: "Date of publication in SHAB (Swiss Official Gazette of Commerce)"
      - name: cantonal_excerpt_web_url
        description: "URL to the cantonal commercial register excerpt"
      - name: delete_date
        description: "Date when the company was deleted/dissolved (if applicable)"
      - name: rab_id
        description: "Register of Auditing Bodies identifier (if applicable)"
      - name: shab_publications_json
        description: "JSON array containing all SHAB publications for this company"
      - name: old_names_json
        description: "JSON array of previous company names"
      - name: audit_firms_json
        description: "JSON array of audit firms associated with the company"
      - name: audit_firm_for_json
        description: "JSON array of companies this entity audits (if applicable)"
      - name: branch_offices_json
        description: "JSON array of branch offices"
      - name: main_offices_json
        description: "JSON array of main offices"
      - name: further_main_offices_json
        description: "JSON array of additional main offices"
      - name: has_taken_over_json
        description: "JSON array of companies that this company has taken over"
      - name: was_taken_over_by_json
        description: "JSON array of companies that have taken over this company"
      - name: translation_json
        description: "JSON object containing translations of company information"
      - name: full_content_json
        description: "Complete original JSON content for reference and debugging" 